chore: fix ownKeys signature
This is a required fix to update to TS 4.2.2. `Reflet.ownKeys` does now return `(string | symbol)[]` since https://github.com/microsoft/TypeScript/commit/562237dfda3ab270a9f91d0e4e4d411ff7bbd844.

Without this commit, we run into the following compilation error:
```
packages/reactivity/src/baseHandlers.ts:195:3 - error TS2322: Type '(target: object) => (string | number | symbol)[]' is not assignable to type '(target: object) => ArrayLike<string | symbol>'.
      Type '(string | number | symbol)[]' is not assignable to type 'ArrayLike<string | symbol>'.
        Index signatures are incompatible.
          Type 'string | number | symbol' is not assignable to type 'string | symbol'.
            Type 'number' is not assignable to type 'string | symbol'.
```